from google_play_scraper import Sort, reviews_all
import pandas as pd
def reviews_all_app():
    reviews_all_app = reviews_all(
        'com.bca.mybca.omni.android',
        lang='id', # defaults to 'en'
        country='id', # defaults to 'us'
        filter_score_with=None # defaults to None (means all score))
    )
    return pd.DataFrame(reviews_all_app)
def data_dict():
    kamus_data = pd.read_excel("https://github.com/nsyamsu23/kamus/raw/main/kamuskatabaku.xlsx")
    kamus_tidak_baku = pd.Series(kamus_data["kata_baku"],index=kamus_data["tidak_baku"]).to_dict()
    return kamus_tidak_baku

def chat_words_mapping():
    chat_words_mapping = {
        'bagu': 'bagus',
        'yg': 'yang',
        'ya': 'ya',
        'sy': 'saya',
        'guru2': 'guru guru',
        'dg': 'dengan',
        'ga': 'tidak',
        'sd': 'sekolah dasar',
        'it': 'itu',
        'tp': 'tapi',
        'bs': 'bisa',
        'jg': 'juga',
        'gk': 'tidak',
        'jd': 'jadi',
        'p5': 'P5',
        'dn': 'dan',
        'lg': 'lagi',
        'dr': 'dari',
        'anak2': 'anak anak',
        'pd': 'pada',
        'bk': 'bimbingan konseling',
        'mudah2an': 'mudah mudahan',
        'benar2': 'benar benar',
        'fitur2': 'fitur fitur',
        'pk': 'pak',
        'sangat2': 'sangat sangat',
        'km': 'kamu',
        'ide2': 'ide ide',
        'ad': 'ada',
        'apa²': 'apa apa',
        'm3nambah': '',
        'gur2': 'guru guru',
        'ujung2nya': 'ujung ujungnya',
        'mw': 'mau',
        'sebelum²nya': 'sebelumnya',
        'akhir2': 'akhir akhir',
        'wbinar2': 'webinar',
        'webinar2': 'webinar',
        'webviewbaru2x': 'webinar baru 2 kali',
        'me4deka': 'merdeka',
        'fitur²': 'fitur fitur',
        "good" : "bagus",
        "@": "di",
        "dagurung": "dari gurung",
        "abis": "habis",
        "ad": "ada",
        "adlh": "adalah",
        "afaik": "as far as i know",
        "ahaha": "haha",
        "aj": "saja",
        "ajep-ajep": "dunia gemerlap",
        "ak": "saya",
        "akika": "aku",
        "akkoh": "aku",
        "akuwh": "aku",
        "alay": "norak",
        "alow": "halo",
        "ambilin": "ambilkan",
        "ancur": "hancur",
        "anjrit": "anjing",
        "anter": "antar",
        "ap2": "apa-apa",
        "apasih": "apa sih",
        "apes": "sial",
        "aps": "apa",
        "aq": "saya",
        "aquwh": "aku",
        "asbun": "asal bunyi",
        "aseekk": "asyik",
        "asekk": "asyik",
        "asem": "asam",
        "aspal": "asli tetapi palsu",
        "astul": "asal tulis",
        "ato": "atau",
        "au ah": "tidak mau tahu",
        "awak": "saya",
        "ay": "sayang",
        "ayank": "sayang",
        "b4": "sebelum",
        "bakalan": "akan",
        "bandes": "bantuan desa",
        "bangedh": "banget",
        "banpol": "bantuan polisi",
        "banpur": "bantuan tempur",
        "basbang": "basi",
        "bcanda": "bercanda",
        "bdg": "bandung",
        "begajulan": "nakal",
        "beliin": "belikan",
        "bencong": "banci",
        "bentar": "sebentar",
        "ber3": "bertiga",
        "beresin": "membereskan",
        "bete": "bosan",
        "beud": "banget",
        "bg": "abang",
        "bgmn": "bagaimana",
        "bgt": "banget",
        "bijimane": "bagaimana",
        "bintal": "bimbingan mental",
        "bkl": "akan",
        "bknnya": "bukannya",
        "blegug": "bodoh",
        "blh": "boleh",
        "bln": "bulan",
        "blum": "belum",
        "bnci": "benci",
        "bnran": "yang benar",
        "bodor": "lucu",
        "bokap": "ayah",
        "boker": "buang air besar",
        "bokis": "bohong",
        "boljug": "boleh juga",
        "bonek": "bocah nekat",
        "boyeh": "boleh",
        "br": "baru",
        "brg": "bareng",
        "bro": "saudara laki-laki",
        "bru": "baru",
        "bs": "bisa",
        "bsen": "bosan",
        "bt": "buat",
        "btw": "ngomong-ngomong",
        "buaya": "tidak setia",
        "bubbu": "tidur",
        "bubu": "tidur",
        "bumil": "ibu hamil",
        "bw": "bawa",
        "bwt": "buat",
        "byk": "banyak",
        "byrin": "bayarkan",
        "cabal": "sabar",
        "cadas": "keren",
        "calo": "makelar",
        "can": "belum",
        "capcus": "pergi",
        "caper": "cari perhatian",
        "ce": "cewek",
        "cekal": "cegah tangkal",
        "cemen": "penakut",
        "cengengesan": "tertawa",
        "cepet": "cepat",
        "cew": "cewek",
        "chuyunk": "sayang",
        "cimeng": "ganja",
        "cipika cipiki": "cium pipi kanan cium pipi kiri",
        "ciyh": "sih",
        "ckepp": "cakep",
        "ckp": "cakep",
        "cmiiw": "correct me if i'm wrong",
        "cmpur": "campur",
        "cong": "banci",
        "conlok": "cinta lokasi",
        "cowwyy": "maaf",
        "cp": "siapa",
        "cpe": "capek",
        "cppe": "capek",
        "cucok": "cocok",
        "cuex": "cuek",
        "cumi": "Cuma miscall",
        "cups": "culun",
        "curanmor": "pencurian kendaraan bermotor",
        "curcol": "curahan hati colongan",
        "cwek": "cewek",
        "cyin": "cinta",
        "d": "di",
        "dah": "deh",
        "dapet": "dapat",
        "de": "adik",
        "dek": "adik",
        "demen": "suka",
        "deyh": "deh",
        "dgn": "dengan",
        "diancurin": "dihancurkan",
        "dimaafin": "dimaafkan",
        "dimintak": "diminta",
        "disono": "di sana",
        "dket": "dekat",
        "dkk": "dan kawan-kawan",
        "dll": "dan lain-lain",
        "dlu": "dulu",
        "dngn": "dengan",
        "dodol": "bodoh",
        "doku": "uang",
        "dongs": "dong",
        "dpt": "dapat",
        "dri": "dari",
        "drmn": "darimana",
        "drtd": "dari tadi",
        "dst": "dan seterusnya",
        "dtg": "datang",
        "duh": "aduh",
        "duren": "durian",
        "ed": "edisi",
        "egp": "emang gue pikirin",
        "eke": "aku",
        "elu": "kamu",
        "emangnya": "memangnya",
        "emng": "memang",
        "endak": "tidak",
        "enggak": "tidak",
        "envy": "iri",
        "ex": "mantan",
        "fax": "facsimile",
        "fifo": "first in first out",
        "folbek": "follow back",
        "fyi": "sebagai informasi",
        "gaada": "tidak ada uang",
        "gag": "tidak",
        "gaje": "tidak jelas",
        "gak papa": "tidak apa-apa",
        "gan": "juragan",
        "gaptek": "gagap teknologi",
        "gatek": "gagap teknologi",
        "gawe": "kerja",
        "gbs": "tidak bisa",
        "gebetan": "orang yang disuka",
        "geje": "tidak jelas",
        "gepeng": "gelandangan dan pengemis",
        "ghiy": "lagi",
        "gile": "gila",
        "gimana": "bagaimana",
        "gino": "gigi nongol",
        "githu": "gitu",
        "gj": "tidak jelas",
        "gmana": "bagaimana",
        "gn": "begini",
        "goblok": "bodoh",
        "golput": "golongan putih",
        "gowes": "mengayuh sepeda",
        "gpny": "tidak punya",
        "gr": "gede rasa",
        "gretongan": "gratisan",
        "gtau": "tidak tahu",
        "gua": "saya",
        "guoblok": "goblok",
        "gw": "saya",
        "ha": "tertawa",
        "haha": "tertawa",
        "hallow": "halo",
        "hankam": "pertahanan dan keamanan",
        "hehe": "he",
        "helo": "halo",
        "hey": "hai",
        "hlm": "halaman",
        "hny": "hanya",
        "hoax": "isu bohong",
        "hr": "hari",
        "hrus": "harus",
        "hubdar": "perhubungan darat",
        "huff": "mengeluh",
        "hum": "rumah",
        "humz": "rumah",
        "ilang": "hilang",
        "ilfil": "tidak suka",
        "imho": "in my humble opinion",
        "imoetz": "imut",
        "item": "hitam",
        "itungan": "hitungan",
        "iye": "iya",
        "ja": "saja",
        "jadiin": "jadi",
        "jaim": "jaga image",
        "jayus": "tidak lucu",
        "jdi": "jadi",
        "jem": "jam",
        "jga": "juga",
        "jgnkan": "jangankan",
        "jir": "anjing",
        "jln": "jalan",
        "jomblo": "tidak punya pacar",
        "jubir": "juru bicara",
        "jutek": "galak",
        "k": "ke",
        "kab": "kabupaten",
        "kabor": "kabur",
        "kacrut": "kacau",
        "kadiv": "kepala divisi",
        "kagak": "tidak",
        "kalo": "kalau",
        "kampret": "sialan",
        "kamtibmas": "keamanan dan ketertiban masyarakat",
        "kamuwh": "kamu",
        "kanwil": "kantor wilayah",
        "karna": "karena",
        "kasubbag": "kepala subbagian",
        "katrok": "kampungan",
        "kayanya": "kayaknya",
        "kbr": "kabar",
        "kdu": "harus",
        "kec": "kecamatan",
        "kejurnas": "kejuaraan nasional",
        "kekeuh": "keras kepala",
        "kel": "kelurahan",
        "kemaren": "kemarin",
        "kepengen": "mau",
        "kepingin": "mau",
        "kepsek": "kepala sekolah",
        "kesbang": "kesatuan bangsa",
        "kesra": "kesejahteraan rakyat",
        "ketrima": "diterima",
        "kgiatan": "kegiatan",
        "kibul": "bohong",
        "kimpoi": "kawin",
        "kl": "kalau",
        "klianz": "kalian",
        "kloter": "kelompok terbang",
        "klw": "kalau",
        "km": "kamu",
        "kmps": "kampus",
        "kmrn": "kemarin",
        "knal": "kenal",
        "knp": "kenapa",
        "kodya": "kota madya",
        "komdis": "komisi disiplin",
        "komsov": "komunis sovyet",
        "kongkow": "kumpul bareng teman-teman",
        "kopdar": "kopi darat",
        "korup": "korupsi",
        "kpn": "kapan",
        "krenz": "keren",
        "krm": "kirim",
        "kt": "kita",
        "ktmu": "ketemu",
        "ktr": "kantor",
        "kuper": "kurang pergaulan",
        "kw": "imitasi",
        "kyk": "seperti",
        "la": "lah",
        "lam": "salam",
        "lamp": "lampiran",
        "lanud": "landasan udara",
        "latgab": "latihan gabungan",
        "lebay": "berlebihan",
        "leh": "boleh",
        "lelet": "lambat",
        "lemot": "lambat",
        "lgi": "lagi",
        "lgsg": "langsung",
        "liat": "lihat",
        "litbang": "penelitian dan pengembangan",
        "lmyn": "lumayan",
        "lo": "kamu",
        "loe": "kamu",
        "lola": "lambat berfikir",
        "louph": "cinta",
        "low": "kalau",
        "lp": "lupa",
        "luber": "langsung, umum, bebas, dan rahasia",
        "luchuw": "lucu",
        "lum": "belum",
        "luthu": "lucu",
        "lwn": "lawan",
        "maacih": "terima kasih",
        "mabal": "bolos",
        "macem": "macam",
        "macih": "masih",
        "maem": "makan",
        "magabut": "makan gaji buta",
        "maho": "homo",
        "mak jang": "kaget",
        "maksain": "memaksa",
        "malem": "malam",
        "mam": "makan",
        "maneh": "kamu",
        "maniez": "manis",
        "mao": "mau",
        "masukin": "masukkan",
        "melu": "ikut",
        "mepet": "dekat sekali",
        "mgu": "minggu",
        "migas": "minyak dan gas bumi",
        "mikol": "minuman beralkohol",
        "miras": "minuman keras",
        "mlah": "malah",
        "mngkn": "mungkin",
        "mo": "mau",
        "mokad": "mati",
        "moso": "masa",
        "mpe": "sampai",
        "msk": "masuk",
        "mslh": "masalah",
        "mt": "makan teman",
        "mubes": "musyawarah besar",
        "mulu": "melulu",
        "mumpung": "selagi",
        "munas": "musyawarah nasional",
        "muntaber": "muntah dan berak",
        "musti": "mesti",
        "muupz": "maaf",
        "mw": "mau",
        "n": "dan",
        "nanam": "menanam",
        "nanya": "bertanya",
        "napa": "kenapa",
        "napi": "narapidana",
        "napza": "narkotika, alkohol, psikotropika, dan zat adiktif ",
        "narkoba": "narkotika, psikotropika, dan obat terlarang",
        "nasgor": "nasi goreng",
        "nda": "tidak",
        "ndiri": "sendiri",
        "ne": "ini",
        "nekolin": "neokolonialisme",
        "nembak": "menyatakan cinta",
        "ngabuburit": "menunggu berbuka puasa",
        "ngaku": "mengaku",
        "ngambil": "mengambil",
        "nganggur": "tidak punya pekerjaan",
        "ngapah": "kenapa",
        "ngaret": "terlambat",
        "ngasih": "memberikan",
        "ngebandel": "berbuat bandel",
        "ngegosip": "bergosip",
        "ngeklaim": "mengklaim",
        "ngeksis": "menjadi eksis",
        "ngeles": "berkilah",
        "ngelidur": "menggigau",
        "ngerampok": "merampok",
        "ngga": "tidak",
        "ngibul": "berbohong",
        "ngiler": "mau",
        "ngiri": "iri",
        "ngisiin": "mengisikan",
        "ngmng": "bicara",
        "ngomong": "bicara",
        "ngubek2": "mencari-cari",
        "ngurus": "mengurus",
        "nie": "ini",
        "nih": "ini",
        "niyh": "nih",
        "nmr": "nomor",
        "nntn": "nonton",
        "nobar": "nonton bareng",
        "np": "now playing",
        "ntar": "nanti",
        "ntn": "nonton",
        "numpuk": "bertumpuk",
        "nutupin": "menutupi",
        "nyari": "mencari",
        "nyekar": "menyekar",
        "nyicil": "mencicil",
        "nyoblos": "mencoblos",
        "nyokap": "ibu",
        "ogah": "tidak mau",
        "ol": "online",
        "ongkir": "ongkos kirim",
        "oot": "out of topic",
        "org2": "orang-orang",
        "ortu": "orang tua",
        "otda": "otonomi daerah",
        "otw": "on the way, sedang di jalan",
        "pacal": "pacar",
        "pake": "pakai",
        "pala": "kepala",
        "pansus": "panitia khusus",
        "parpol": "partai politik",
        "pasutri": "pasangan suami istri",
        "pd": "pada",
        "pede": "percaya diri",
        "pelatnas": "pemusatan latihan nasional",
        "pemda": "pemerintah daerah",
        "pemkot": "pemerintah kota",
        "pemred": "pemimpin redaksi",
        "penjas": "pendidikan jasmani",
        "perda": "peraturan daerah",
        "perhatiin": "perhatikan",
        "pesenan": "pesanan",
        "pgang": "pegang",
        "pi": "tapi",
        "pilkada": "pemilihan kepala daerah",
        "pisan": "sangat",
        "pk": "pak",
        "plg": "paling",
        "pmrnth": "pemerintah",
        "polantas": "polisi lalu lintas",
        "ponpes": "pondok pesantren",
        "pp": "pulang pergi",
        "prg": "pergi",
        "prnh": "pernah",
        "psen": "pesan",
        "pst": "pasti",
        "pswt": "pesawat",
        "pw": "posisi nyaman",
        "qmu": "kamu",
        "rakor": "rapat koordinasi",
        "ranmor": "kendaraan bermotor",
        "re": "reply",
        "ref": "referensi",
        "rehab": "rehabilitasi",
        "rempong": "sulit",
        "repp": "balas",
        "restik": "reserse narkotika",
        "rhs": "rahasia",
        "rmh": "rumah",
        "ru": "baru",
        "ruko": "rumah toko",
        "rusunawa": "rumah susun sewa",
        "ruz": "terus",
        "saia": "saya",
        "salting": "salah tingkah",
        "sampe": "sampai",
        "samsek": "sama sekali",
        "sapose": "siapa",
        "satpam": "satuan pengamanan",
        "sbb": "sebagai berikut",
        "sbh": "sebuah",
        "sbnrny": "sebenarnya",
        "scr": "secara",
        "sdgkn": "sedangkan",
        "sdkt": "sedikit",
        "se7": "setuju",
        "sebelas dua belas": "mirip",
        "sembako": "sembilan bahan pokok",
        "sempet": "sempat",
        "sendratari": "seni drama tari",
        "sgt": "sangat",
        "shg": "sehingga",
        "siech": "sih",
        "sikon": "situasi dan kondisi",
        "sinetron": "sinema elektronik",
        "siramin": "siramkan",
        "sj": "saja",
        "skalian": "sekalian",
        "sklh": "sekolah",
        "skt": "sakit",
        "slesai": "selesai",
        "sll": "selalu",
        "slma": "selama",
        "slsai": "selesai",
        "smpt": "sempat",
        "smw": "semua",
        "sndiri": "sendiri",
        "soljum": "sholat jumat",
        "songong": "sombong",
        "sory": "maaf",
        "sosek": "sosial-ekonomi",
        "sotoy": "sok tahu",
        "spa": "siapa",
        "sppa": "siapa",
        "spt": "seperti",
        "srtfkt": "sertifikat",
        "stiap": "setiap",
        "stlh": "setelah",
        "suk": "masuk",
        "sumpek": "sempit",
        "syg": "sayang",
        "t4": "tempat",
        "tajir": "kaya",
        "tau": "tahu",
        "taw": "tahu",
        "td": "tadi",
        "tdk": "tidak",
        "teh": "kakak perempuan",
        "telat": "terlambat",
        "telmi": "telat berpikir",
        "temen": "teman",
        "tengil": "menyebalkan",
        "tepar": "terkapar",
        "tggu": "tunggu",
        "tgu": "tunggu",
        "thankz": "terima kasih",
        "thn": "tahun",
        "tilang": "bukti pelanggaran",
        "tipiwan": "TvOne",
        "tks": "terima kasih",
        "tlp": "telepon",
        "tls": "tulis",
        "tmbah": "tambah",
        "tmen2": "teman-teman",
        "tmpah": "tumpah",
        "tmpt": "tempat",
        "tngu": "tunggu",
        "tnyta": "ternyata",
        "tokai": "tai",
        "toserba": "toko serba ada",
        "tpi": "tapi",
        "trdhulu": "terdahulu",
        "trima": "terima kasih",
        "trm": "terima",
        "trs": "terus",
        "trutama": "terutama",
        "ts": "penulis",
        "tst": "tahu sama tahu",
        "ttg": "tentang",
        "tuch": "tuh",
        "tuir": "tua",
        "tw": "tahu",
        "u": "kamu",
        "ud": "sudah",
        "udah": "sudah",
        "ujg": "ujung",
        "ul": "ulangan",
        "unyu": "lucu",
        "uplot": "unggah",
        "urang": "saya",
        "usah": "perlu",
        "utk": "untuk",
        "valas": "valuta asing",
        "w/": "dengan",
        "wadir": "wakil direktur",
        "wamil": "wajib militer"
    }
    return chat_words_mapping
def emojiDict():
    emoji_dict = {
        "\U0001F600": "senang",  # Grinning Face
        "\U0001F601": "sangat senang",  # Grinning Face with Smiling Eyes
        "\U0001F602": "tertawa terbahak",  # Face with Tears of Joy
        "\U0001F603": "senang",  # Smiling Face with Open Mouth
        "\U0001F604": "sangat senang",  # Smiling Face with Open Mouth and Smiling Eyes
        "\U0001F605": "lega",  # Smiling Face with Open Mouth and Cold Sweat
        "\U0001F606": "tertawa lebar",  # Smiling Face with Open Mouth and Tightly Closed Eyes
        "\U0001F609": "menggoda",  # Winking Face
        "\U0001F60A": "bahagia",  # Smiling Face with Smiling Eyes
        "\U0001F60B": "nikmat",  # Face Savoring Delicious Food
        "\U0001F60C": "lega",  # Relieved Face
        "\U0001F60D": "jatuh cinta",  # Smiling Face with Heart-Eyes
        "\U0001F60E": "keren",  # Smiling Face with Sunglasses
        "\U0001F60F": "sinis",  # Smirking Face
        "\U0001F612": "takut",  # Unamused Face
        "\U0001F613": "keringat",  # Face with Cold Sweat
        "\U0001F614": "sedih",  # Pensive Face
        "\U0001F616": "sakit",  # Confounded Face
        "\U0001F618": "mencium",  # Face Throwing a Kiss
        "\U0001F621": "marah",  # Pouting Face
        "\U0001F622": "menangis",  # Crying Face
        "\U0001F623": "frustasi",  # Persevering Face
        "\U0001F624": "kesal",  # Face with Look of Triumph
        "\U0001F625": "cemas",  # Disappointed but Relieved Face
        "\U0001F628": "takut",  # Fearful Face
        "\U0001F629": "lelah",  # Weary Face
        "\U0001F62A": "mengantuk",  # Sleepy Face
        "\U0001F62B": "lelah",  # Tired Face
        "\U0001F62D": "sangat sedih",  # Loudly Crying Face
        "\U0001F630": "terkejut",  # Face with Open Mouth and Cold Sweat
        "\U0001F631": "ketakutan",  # Face Screaming in Fear
        "\U0001F632": "terkejut",  # Astonished Face
        "\U0001F633": "malu",  # Flushed Face
        "\U0001F635": "pingsan",  # Dizzy Face
        "\U0001F637": "sakit",  # Face with Medical Mask
        "\U0001F641": "sedih",  # Slightly Frowning Face
        "\U0001F642": "tersenyum",  # Slightly Smiling Face
        "\U0001F643": "terbalik",  # Upside-Down Face
        "\U0001F644": "melirik",  # Face with Rolling Eyes
        "\U0001F44D": "setuju",  # Thumbs Up
        "\U0001F44E": "tidak setuju",  # Thumbs Down
        "\U0001F44C": "ok",  # OK Hand
        "\U0001F44F": "tepuk tangan",  # Clapping Hands
        "\U0001F44A": "tinju",  # Fisted Hand Sign
        "\U0001F91E": "menyilang jari",  # Crossed Fingers
        "\U0001F64C": "angkat tangan",  # Raising Hands
        "\U0001F64F": "berdoa",
        "\U0001F97A":""# Folded Hands
    }    
    return emoji_dict